language: ruby

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head

env:
  - global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22

dist: trusty
sudo: required

before_install:
  - sudo usermod -p `openssl passwd -1 'travis'` travis
  - gem --version

bundler_args: --without guard integration

script:
  - bundle exec rake
  - bundle install --with integration
  - export KITCHEN_YAML=.kitchen.ci.yml
  - bundle exec kitchen verify ubuntu

branches:
  only:
  - master

matrix:
  include:
    - rvm: 2.2.5
      # To run the proxy tests we need additional gems than what Test Kitchen normally uses
      # for testing
      gemfile: Gemfile.proxy_tests
      before_install:
        - sudo usermod -p `openssl passwd -1 'travis'` travis
        - gem install bundler
        - sudo apt-get update
        - sudo apt-get -y install squid3 git curl
      env:
        - global:
          - machine_user=travis
          - machine_pass=travis
          - machine_port=22
          - PROXY_TESTS_DIR=proxy_tests/files/default/scripts
          - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo
          - KITCHEN_YAML=/home/travis/build/test-kitchen/test-kitchen/.kitchen.proxy.yml

      script:
        - bundle exec kitchen --version
        - git clone https://github.com/chef/proxy_tests.git
        - rvmsudo -E bundle exec bash $PROXY_TESTS_DIR/run_tests.sh kitchen \* \* /tmp/out.txt
      after_script:
        - cat /tmp/out.txt
        - sudo cat /var/log/squid3/cache.log
        - sudo cat /var/log/squid3/access.log
  allow_failures:
    - rvm: ruby-head

notifications:
  irc: "chat.freenode.net#kitchenci"

addons:
  code_climate:
    repo_token:
      secure: "lcqi3hbalLTinxwsl+um1aN1dgijBrODSMseGEJMJGkofz3VZ+Ofuuwp9x9VjvewuiUFHsiPD5SQ6hx8N+L3wXB6qA+HTmIrXecL7VjehbImEyOuu4/++vcTdpTINAd2Qt/KuJ1eY0okSwVmvtX1VD8gYD8yrlMKdj6uexf8Bgs="
