---
trigger:
  batch: true
  branches:
    include:
      - main
pr:
  autoCancel: true
  branches:
    include:
      - main

variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle
  CHEF_LICENSE: accept-no-persist

stages:
  - stage: Build
    jobs:
      - job: Windows
        strategy:
          matrix:
            Windows_Ruby26:
              version: 2.6
              machine_user: test_user
              machine_pass: Pass@word1
              machine_port: 5985
              KITCHEN_YAML: kitchen.windows.yml
            Windows_Ruby27:
              version: 2.7
              machine_user: test_user
              machine_pass: Pass@word1
              machine_port: 5985
              KITCHEN_YAML: kitchen.windows.yml
            WindowsProduct_Ruby27:
              version: 2.7
              machine_user: test_user
              machine_pass: Pass@word1
              machine_port: 5985
              KITCHEN_YAML: kitchen.windows-product.yml
            WindowsProduct_Ruby30:
              version: 3.0
              machine_user: test_user
              machine_pass: Pass@word1
              machine_port: 5985
              KITCHEN_YAML: kitchen.windows-product.yml
        pool:
          vmImage: windows-latest
        steps:
          - task: Cache@2
            inputs:
              key: gems | $(Agent.OS) | "$(version)" | test-kitchen.gemspec | Gemfile | Gemfile.proxy_tests
              path: $(BUNDLE_PATH)
            displayName: Cache gems
          - task: UseRubyVersion@0
            inputs:
              versionSpec: $(version)
              addToPath: true
          - script: |
              echo "ruby version:"
              ruby --version
              echo "gem version:"
              gem --version
            displayName: Show Ruby Version
          - script: |
              gem install bundler --quiet
              echo "bundler version:"
              bundler --version
            displayName: Install Bundler
          - script: |
              bundle install || bundle install || bundle install
            displayName: Bundle Install Dependencies
          - script: |
              bundle exec rake unit && bundle exec rake quality
            displayName: Run Tests
            env:
              SPEC_OPTS: --format progress
          - script: |
              winrm.cmd quickconfig -q
              net user /add %machine_user% %machine_pass%
              net localgroup administrators %machine_user% /add
              bundle install --with integration
              bundle exec kitchen verify windows
            displayName: Run Converge
      - job: Mac
        strategy:
          matrix:
            Mac_Ruby26:
              version: 2.6
            Mac_Ruby27:
              version: 2.7
            Mac_Ruby30:
              version: 3.0
        pool:
          vmImage: "macOS-latest"
        steps:
          - task: Cache@2
            inputs:
              key: gems | $(Agent.OS) | "$(version)" | test-kitchen.gemspec | Gemfile | Gemfile.proxy_tests
              path: $(BUNDLE_PATH)
              cacheHitVar: CACHE_RESTORED
            displayName: Cache gems
          - task: UseRubyVersion@0
            inputs:
              versionSpec: $(version)
              addToPath: true
          - script: |
              echo "ruby version:"
              ruby --version
              echo "gem version:"
              gem --version
            displayName: Show Ruby Version
          - script: |
              gem install bundler --quiet
              echo "bundler version:"
              bundler --version
            displayName: Install Bundler
          - script: |
              bundle install || bundle install || bundle install
            displayName: Bundle Install Dependencies
          - script: |
              bundle exec rake
            displayName: Run Tests
            env:
              SPEC_OPTS: --format progress
      - job: Linux
        strategy:
          matrix:
            Linux_Ruby26:
              version: 2.6
            Linux_Ruby27:
              version: 2.7
            Linux_Ruby30:
              version: 3.0
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Cache@2
            inputs:
              key: gems | $(Agent.OS) | "$(version)" | test-kitchen.gemspec | Gemfile | Gemfile.proxy_tests
              path: $(BUNDLE_PATH)
              cacheHitVar: CACHE_RESTORED
            displayName: Cache gems
          - task: UseRubyVersion@0
            inputs:
              versionSpec: $(version)
              addToPath: true
          - script: |
              echo "ruby version:"
              ruby --version
              echo "gem version:"
              gem --version
            displayName: Show Ruby Version
          - script: |
              gem install bundler --quiet
              echo "bundler version:"
              bundler --version
            displayName: Install Bundler
          - script: |
              bundle install || bundle install || bundle install
            displayName: Bundle Install Dependencies
          - script: |
              bundle exec rake
            displayName: Run Tests
            env:
              SPEC_OPTS: --format progress
          - script: |
              bundle install --with integration
              bundle exec kitchen test
            displayName: Run Integration Tests
            env:
              KITCHEN_YAML: kitchen.dokken.yml
      - job: LinuxProduct
        variables:
          MACHINE_USER: kitchen
          MACHINE_PASS: K1tch3nY@ml!
          MACHINE_PORT: 22
          version: 2.7
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Cache@2
            inputs:
              key: gems | $(Agent.OS) | "$(version)" | test-kitchen.gemspec | Gemfile | Gemfile.proxy_tests
              path: $(BUNDLE_PATH)
              cacheHitVar: CACHE_RESTORED
            displayName: Cache gems
          - task: UseRubyVersion@0
            inputs:
              versionSpec: $(version)
              addToPath: true
          - script: |
              echo "ruby version:"
              ruby --version
              echo "gem version:"
              gem --version
            displayName: Show Ruby Version
          - script: |
              gem install bundler --quiet
              echo "bundler version:"
              bundler --version
            displayName: Install Bundler
          - script: |
              bundle install || bundle install || bundle install
            displayName: Bundle Install Dependencies
          - script: |
              sudo -E useradd $MACHINE_USER --shell /bin/bash --create-home
              sudo -E usermod -p `openssl passwd -1 $MACHINE_PASS` $MACHINE_USER
              sudo -E usermod -aG sudo $MACHINE_USER
            displayName: Add local user
          - script: |
              sudo mkdir -p /var/run/sshd
              sudo service ssh restart
            displayName: Start SSHD
          - script: |
              sudo echo 'Defaults	secure_path="/opt/hostedtoolcache/Ruby/2.7.1/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"' | sudo tee /etc/sudoers.d/kitchen
              sudo echo "" | sudo tee -a /etc/sudoers.d/kitchen
              sudo echo "kitchen ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/kitchen
              sudo echo "" | sudo tee -a /etc/sudoers.d/kitchen
            displayName: Update path and sudo privs for local user
          - script: |
              bundle exec rake
            displayName: Run Tests
            env:
              SPEC_OPTS: --format progress
          - script: |
              bundle install --with integration
              bundle exec kitchen test
            displayName: Run Integration Tests
            env:
              KITCHEN_YAML: kitchen.linux-product.yml
      - job: Proxy_Tests
        variables:
          MACHINE_USER: kitchen
          MACHINE_PASS: K1tch3nY@ml!
          MACHINE_PORT: 22
          KITCHEN_YAML: ../../../../../../../kitchen.proxy.yml
          PROXY_TESTS_DIR: proxy_tests/files/default/scripts
          PROXY_TESTS_REPO: proxy_tests/files/default/scripts/repo
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseRubyVersion@0
            inputs:
              versionSpec: 2.7
              addToPath: true
          - script: |
              echo "ruby version:"
              ruby --version
              echo "gem version:"
              gem --version
            displayName: Show Ruby Version
          - script: |
              gem install bundler --quiet
              echo "bundler version:"
              bundler --version
            displayName: Install Bundler
          - script: |
              sudo -E useradd $MACHINE_USER --shell /bin/bash --create-home
              sudo -E usermod -p `openssl passwd -1 $MACHINE_PASS` $MACHINE_USER
              sudo -E usermod -aG sudo $MACHINE_USER
            displayName: Add local user
          - script: |
              sudo mkdir -p /var/run/sshd
              sudo service ssh restart

              sudo apt-get update
              sudo apt-get -y install squid3 git curl
              git clone https://github.com/smurawski/proxy_tests.git
            displayName: Install and configure dependencies
          - script: |
              sudo echo 'Defaults	secure_path="/opt/hostedtoolcache/Ruby/2.7.1/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"' | sudo tee /etc/sudoers.d/kitchen
              sudo echo "" | sudo tee -a /etc/sudoers.d/kitchen
              sudo echo "kitchen ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/kitchen
              sudo echo "" | sudo tee -a /etc/sudoers.d/kitchen
            displayName: Work around the problem with sudo and tool paths
          - script: |
              sudo -E bundle install --gemfile Gemfile.proxy_tests
              sudo -E bundle exec bash $PROXY_TESTS_DIR/run_tests.sh kitchen \* \* /tmp/out.txt
              cat /tmp/out.txt

              echo ""
              echo "===================="
              echo "Tests finished."
              echo "===================="
              echo ""

              sudo cat /var/log/squid/cache.log
              sudo cat /var/log/squid/access.log
            displayName: Run proxy tests
  - stage:
    dependsOn: Build
    jobs:
      - job: Package
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'), notIn(variables['Build.Reason'], 'PullRequest'))
        pool:
          imageName: "ubuntu-16.04"
        steps:
          - task: UseRubyVersion@0
            inputs:
              versionSpec: 2.6
              addToPath: true
          - script: |
              gem install bundler --quiet
              bundle install || bundle install || bundle install
              bundle exec rake build
            displayName: Package Gem
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: Release Build"
            inputs:
              PathtoPublish: ./pkg
              ArtifactName: gem
              ArtifactType: Container
